### PR TITLE
NEW: Improve portability

### PR DESCRIPTION
**Pull request by sminnee**
The server launcher is now a composer bin command, rather than a
SilverStripe build tasks, which makes it compatible with both 3.x
and 4.x without changes.

Class loading utilises composer, and the serve module can be either
at <root>/server or vendor/silverstripe/serve, which is more orthodox.

The type: silverstripe-module marker is no longer needed as this just
controls the install location of the module.

Reliance on BASE_PATH and FRAMEWORK_PARH, which are set by the composer
autoloader whenever silverstripe/framework is included, make this more
resilient to filesystem structure changes.

The up-shot of all this is that serve can be listed as a dev-dependency
of a SilverStripe module and used to do integration testing of that
module, provided other work around SilverStripe’s filesystem decoupling
also happens.

---

To do before merge:
- [x] Get silverstripe-framework's behat build running using this
- [ ] Get silverstripe-cms's behat build running using this

### CODE REVIEW

**Comment by sminnee** [comment]
The change is pretty extensive; I'm happy to tweak any parts of this that you don't like, but I'm keen  to get a more portable extension ready for my own purposes.

**Comment by assertchris** [comment]
I'm doing something silly, and I can't get this to work. I create a new SilverStripe installation (`composer create-project silverstripe/installer silverstripe-serve-3-4 ^3.4`), and install this version of the module (`composer require silverstripe/serve dev-master#cb6a64c318fd6a719d1e9cb5278a8aa4e8731c08`). After a few bouts of `dev/build flush=1` and `composer du`, the classes defined in this module aren't detected by the `serve` script.

Similarly, `composer create-project silverstripe/installer silverstripe-serve-4-0 4.0.x-dev@dev`, `git clone git@github.com:assertchris/silverstripe-serve.git serve`, `git checkout -b sminnee-improve-portability master`, `git pull https://github.com/sminnee/silverstripe-serve.git improve-portability`, and subsequent builds/du's lead to the same error messages. 

Will keep trying to figure out what I'm doing wrong.

**Comment by sminnee** [comment]
Hrm, I'll see if I can get to the bottom of it tomorrow. I didn't test the autoloader directly; composer dump-autoload really needs to be fixed to read from the local repos' copies of composer.json.

**Comment by sminnee** [comment]
Once we sort this out I guess it's a 2.0 release? Lol... Maybe wait until I've got it working with the new builder, I guess.

**Comment by sminnee** [comment]
@assertchris it doesn't seem that composer lets you test this without merging. 

`composer require silverstripe/serve dev-master#cb6a64c318fd6a719d1e9cb5278a8aa4e8731c08` uses the meta-data of the current master branch to do dependency resolution before switching to that SHA. It doesn't grab my composer.json changes.

**Comment by sminnee** [comment]
Ah, figured it out:
- Clone my branch somewhere locally: `/path/sam-serve`
- Add this to your project's composer.json "repositories"

``` json
"repositories": [{ "type": "path", "url": "/path/sam-serve" }]
```
- Run `composer require silverstripe/serve dev-improve-portability`
  The local clone will be used as the source repo.

**Comment by sminnee** [comment]
I picked up a typo in composer.json and I was having issue with the `^4.0` dependency when pulling into framework branches, which will get painful if we use this as part of framework's travis build (which is my goal for behat tests). Changing to >=3.2 worked; we can amend after 4.0 stable comes out.

**Comment by sminnee** [comment]
Related: https://github.com/silverstripe/silverstripe-framework/pull/5986/commits/9dfaeaf26439d9191255ea83273cec27551f2841

Right now I'm just hard-pulling in my working branch into that build; I expect you'll be distracted for a while! ;-)

**Comment by assertchris** [comment]
@sminnee just ping here when you think you're done and I'll merge and start testing again. I don't mind merging and then testing, but I don't want to merge before you're proper done cause then it's a hassle for you to add more commits.

**Comment by sminnee** [comment]
Ok I've got this to the point where I'm comfortable merging. I notice you've given me commit rights now so I might just click the button, since you've got other things on your mind ;-)

I've got the behat build running and passing via serve over here.

**Comment by assertchris** [comment]
Was holding off till you checked that second checkbox. I'll give things a test.

**Pull request merged**
